---

# docker run --interactive --tty fedora bash
# dnf install ansible git-core
# ansible-pull -U https://github.com/SebastianThorn/new_fedora_host new_fedora_host.yml

- name: Base Fedora install
  hosts: localhost
  become: true

  tasks:
  - name: Update all packages
    dnf:
      name: "*"
      state: latest

  - name: Install packages
    dnf:
      name:
        - emacs-nox
        - git-core
        - procps-ng
        - tmux

